# -*- coding: utf-8 -*-
"""DAV Lab Exercise 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ia9UzwBYgs4YsynX9OFhN5tMOc6n-f-0
"""

pip install numpy

pip install scipy

pip install  jupyter statsmodels

pip install  pandas

pip install matplotlib

pip install seaborn

pip install plotly

pip install bokeh

import numpy as np
print("NumPy Version:", np.__version__)

import pandas as pd
print("Pandas Version:", pd.__version__)

import matplotlib
print("Matplotlib Version:", matplotlib.__version__)

import seaborn as sns
print("Seaborn Version:", sns.__version__)

import statsmodels.api as sm
print("Statsmodels Version:", sm.__version__)

import scipy
print("SciPy Version:", scipy.__version__)

import plotly
print("Plotly Version:", plotly.__version__)

import bokeh
print("Bokeh Version:", bokeh.__version__)

import jupyterlab
print("JupyterLab Version:", jupyterlab.__version__)