# -*- coding: utf-8 -*-
"""dav exp 2c

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JQW0MfSS6hdjb-tWcTFsNOkvp-iFkFNZ
"""

import pandas as pd

# ==========================================
# STEP 1: Reading Data from Different Sources
# ==========================================

# 1. Read from a local CSV file
text_df = pd.read_csv('student_performance_500.csv')

# 2. Read from a local Excel file
excel_df = pd.read_excel('Coca Cola Co.xlsx', sheet_name='COCA COLA CO')

# 3. Read from a web-based CSV source
web_url = 'https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv'
web_df = pd.read_csv(web_url)

# ==========================================
# STEP 2: Displaying the Head of Datasets
# ==========================================
print("--- Text/CSV Data Head ---")
print(text_df.head(), "\n")

print("--- Excel Data Head ---")
print(excel_df.head(), "\n")

print("--- Web Data Head ---")
print(web_df.head(), "\n")

# ==========================================
# STEP 3: Handling Missing Values (Data Cleaning)
# ==========================================
# Note: fillna(method='ffill') is deprecated.
# We use direct .ffill() and .bfill() to prevent warnings.
text_df.ffill(inplace=True)
excel_df.bfill(inplace=True)
web_df.dropna(inplace=True)

# ==========================================
# STEP 4: Saving Processed Data
# ==========================================
text_df.to_csv('processed_text.csv', index=False)
excel_df.to_excel('processed_excel.xlsx', index=False)

print("Processed datasets successfully saved!")

xls = pd.ExcelFile('Coca Cola Co.xlsx')
print(xls.sheet_names)