# -*- coding: utf-8 -*-
"""dav exp 2dipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KHnV9GJmQM-lR6ALuousQ_Yv5HSTsirv
"""

import pandas as pd
import seaborn as sns

# ==========================================
# STEP 1: Load the Iris Dataset
# ==========================================
# We load the dataset using seaborn's built-in datasets
df = sns.load_dataset('iris')

# ==========================================
# STEP 2: Basic Exploration
# ==========================================
print("--- First 5 Rows of the Dataset ---")
print(df.head())
print("\n--- Dataset Information ---")
df.info()

# ==========================================
# STEP 3: Descriptive Analytics (Basic Statistics)
# ==========================================
print("\n--- Summary Statistics (Describe) ---")
print(df.describe())

# Computing specific statistics for numerical columns
numerical_cols = df.select_dtypes(include=['float64', 'int64'])

print("\n--- Mean of Numerical Columns ---")
print(numerical_cols.mean())

print("\n--- Median of Numerical Columns ---")
print(numerical_cols.median())

print("\n--- Mode of Columns ---")
print(df.mode().iloc[0])  # Mode can include the categorical 'species' column

print("\n--- Standard Deviation ---")
print(numerical_cols.std())

print("\n--- Variance ---")
print(numerical_cols.var())

# ==========================================
# STEP 4: Grouped Descriptive Analytics
# ==========================================
# Analyzing statistics grouped by species
print("\n--- Mean Grouped by Species ---")
grouped_mean = df.groupby('species').mean()
print(grouped_mean)

from google.colab import drive
drive.mount('/content/drive')